### ISSUE TITLE
Executor: investigate reproducible race condition-related failure in long stress test run

### ISSUE THREAD

**Issue by andvgal** [futoin/core-js-ri-executor#24]

**Comment by andvgal** [comment]
Error log: 
```
S:24606 F:1707 T:27078 MEMUSED:94954096/146898176@164884480

/www/devxa/core-js-ri-executor/node_modules/futoin-asyncsteps/lib/asyncstep_protector.js:471
        throw Error( futoin_errors.InternalError, 'Unexpected call, object is 
              ^
SERVER MEMUSED:60657744/97449472@113848320
Error: InternalError
    at Error (<anonymous>)
    at Object.ASPProto._sanityCheck (/www/devxa/core-js-ri-executor/node_modules/futoin-asyncsteps/lib/asyncstep_protector.js:471:15)
    at Object.ASPProto.success (/www/devxa/core-js-ri-executor/node_modules/futoin-asyncsteps/lib/asyncstep_protector.js:86:10)
    at Object._onImmediate (/www/devxa/core-js-ri-executor/node_modules/futoin-asyncsteps/lib/asyncstep_protector.js:300:42)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```
